#! /bin/bash

## Colors ##
RESET="\033[0m"
BOLD="\033[1m"
UNDERLINE="\033[4m"
UNDERLINE_OFF="\033[24m"
YELLOW="\033[33m"
GREEN="\033[32m"
CYAN="\033[36m"
RED="\033[31m"

## Config ##
USER=username
BACKUP_SERVER=iporhostname
# Must be escaped
NAME="Username\'s\ MacBook\ Pro"

echo -e "${BOLD}${YELLOW}${UNDERLINE}     ## CONFIG ##       ${RESET}"
echo -e "${YELLOW}USERNAME	${UNDERLINE}${USER}${RESET}"
echo -e "${YELLOW}SERVER		${UNDERLINE}${BACKUP_SERVER}${RESET}"
echo -e "${YELLOW}NAME		${UNDERLINE}${NAME}${RESET}\n"


################

if [[ "$1" == "--music" || "$1" == "-m" ]];
  then
    if [[ "$2" == "-d" || "$2" == "--delete" ]]
      then
        echo -e "${BOLD}${RED}${UNDERLINE} ## Backing up and deleting old Music ## ${RESET}"
	echo -en "${RED}"
	rsync -avh --progress  --delete  ~/Music $USER@$BACKUP_SERVER:"~/$NAME/"	
	echo -e "${RESET}"
      else
        echo -e "${BOLD}${CYAN}${UNDERLINE} ## Backing up Music ## ${RESET}"
	echo -en "${CYAN}"
	rsync -avh --progress  ~/Music $USER@$BACKUP_SERVER:"~/$NAME/"	
	echo -e "${RESET}"
    fi
fi

if [[ "$1" == "--pictures" || "$1" == "-p" ]];
  then
    if [[ "$2" == "-d" || "$2" == "--delete" ]]
      then
        echo -e "${BOLD}${RED}${UNDERLINE} ## Backing up and deleting old Pictures ## ${RESET}"
	echo -en "${RED}"
	rsync -avh --progress  --delete  ~/Pictures $USER@$BACKUP_SERVER:"~/$NAME/"	
	echo -e "${RESET}"
      else
        echo -e "${BOLD}${CYAN}${UNDERLINE} ## Backing up Pictures ## ${RESET}"
	echo -en "${CYAN}"
	rsync -avh --progress  ~/Pictures $USER@$BACKUP_SERVER:"~/$NAME/"	
	echo -e "${RESET}"
    fi
fi

if [[ "$1" == "--all" || "$1" == "-a" ]];
  then
    if [[ "$2" == "-d" || "$2" == "--delete" ]]
      then
        echo -e "${BOLD}${RED}${UNDERLINE} ## Backing up and deleting old Content ## ${RESET}"
	echo -en "${RED}"
	rsync -avh --progress --exclude 'Library' --exclude '.MacOSX' --delete  ~/ $USER@$BACKUP_SERVER:"~/$NAME/"
	echo -e "${RESET}"
      else
        echo -e "${BOLD}${CYAN}${UNDERLINE} ## Backing up everything ## ${RESET}"
	echo -en "${CYAN}"
	rsync -avh --progress --exclude 'Library' --exclude '.MacOSX'  ~/ $USER@$BACKUP_SERVER:"~/$NAME/"	
	echo -e "${RESET}"
    fi
fi

if [[ "$1x" == "x" ]];
  then
    echo -e "${BOLD}Automates backup process for content in your home folder to a specified server. Before first run you must configure your username and server address.${RESET}\n"
    echo -e "Usage ./backup {-m,--music|-p,--pictures|-a,--all} {-d,--delete}\n"
    echo "-m,--music	Backup the entire Music folder."
    echo "-p,--pictures	Backup the entire Pictures folder."
    echo "-a,--all	Backup your entire home directory"
    echo "-d,--delete	Delete files on the server that are no longer present on this machine."
    echo -e "\nCopyright Andrew Hood, 2013\n"
fi



