#! /bin/bash

## Config Section - REPLACE THESE VALUES WITH YOURS  ##

# default USER=username
USER=username

#default BACKUP_SERVER=remotehost
BACKUP_SERVER=remotehost

# default NAME="Username\'s MacBook\ Pro"; Must be escaped.
NAME="Username\'s\ MacBook\ Pro"

# default RSYNC_OPTIONS="-avh --progress"; These options are passed directly to rsync.
RSYNC_OPTIONS="-avh --progress"
## END CONFIG SECTION ##

## Colors ##
RESET="\033[0m"
BOLD="\033[1m"
UNDERLINE="\033[4m"
UNDERLINE_OFF="\033[24m"
YELLOW="\033[33m"
GREEN="\033[32m"
MAGENTA="\033[35m"
CYAN="\033[36m"
RED="\033[31m"
## END COLORS ##


## Check if Config Section has been edited ##
echo -e "${BOLD}${YELLOW}${UNDERLINE}     ## CONFIG ##       ${RESET}"
## Check for USER
if [[ "${USER}" == "username" ]];
  then
    echo -e "${BOLD}${RED}USER must be set. Edit ./backup and change the value of USER in Config section.${RESET}"
  else
    echo -e "${YELLOW}USER		${UNDERLINE}${USER}${RESET}"
fi
## Check for BACKUP_SERVER
if [[ "${BACKUP_SERVER}" == "remotehost" ]];
  then
    echo -e "${BOLD}${RED}BACKUP_SERVER must be set. Edit ./backup and change the value of BACKUP_USER in Config section.${RESET}"
  else 
    echo -e "${YELLOW}BACKUP_SERVER	${UNDERLINE}${BACKUP_SERVER}${RESET}"
fi
## Check for NAME
if [[ "${NAME}" == "Username\'s\ MacBook\ Pro" ]];
  then
    echo -e "${BOLD}${RED}NAME must be set. Edit ./backup and change the value of NAME in Config section.${RESET}"
  else
    echo -e "${YELLOW}NAME		${UNDERLINE}${NAME}${RESET}"
fi
## END CONFIG CHECK ##


## ECHO USAGE IF NO PARAMS ##
if [[ "$1x" == "x" ]];
  then
    echo -e "\n${BOLD}Automates backup process for content in your home folder to a specified server. Before first run you must configure your username and server address.${RESET}\n"
    echo -e "Usage ./backup {-m,--music|-p,--pictures|-a,--all} {-b,--backup|-d,--delete|-r,--restore}\n"
    echo "-m,--music	Backup the entire Music folder."
    echo "-p,--pictures	Backup the entire Pictures folder."
    echo "-a,--all	Backup your entire home directory"
    echo "-b,--backup   Backup files on this computer to the server. This is the default option."
    echo "-d,--delete	Delete files on the server that are no longer present on this machine."
    echo "-r,--restore 	Restore files that exist on the server but are no longer present on this machine."
    echo -e "\nCopyright Andrew Hood, 2013\n"
fi
## END USAGE ##


## EXIT if USER BACKUP_SERVER or NAME is not set. ## 
if [[ "${USER}" == "username" || "${BACKUP_SERVER}" == "remotehost" || "${NAME}" == "Username\'s\ MacBook\ Pro" ]];
  then
    echo -e "${BOLD}${RED}Config incomplete, exiting.${RESET}";
    exit 1
fi
## END EXIT IF CONFIG INCOMPLETE ##

## BEGIN BACKUP PROGRAM ##
if [[ "$1" == "--music" || "$1" == "-m" ]];
  then
    if [[ "$2" == "-r" || "$2" == "--restore" ]]
      then
        echo -e "${BOLD}${MAGENTA}${UNDERLINE} ## Restoring Music to your computer ##${RESET}"
        echo -en "${MAGENTA}"
        rsync ${RSYNC_OPTIONS} $USER@$BACKUP_SERVER:"~/$NAME/Music" ~/
        echo -e "${RESET}"
    fi
    if [[ "$2" == "-d" || "$2" == "--delete" ]]
      then
        echo -e "${BOLD}${RED}${UNDERLINE} ## Backing up and deleting old Music ## ${RESET}"
      	echo -en "${RED}"
      	rsync ${RSYNC_OPTIONS}  --delete  ~/Music $USER@$BACKUP_SERVER:"~/$NAME/"	
      	echo -e "${RESET}"  
    fi
    if [[ "$2" == "-b" || "$2" == "--backup" || "$2x" == "x" ]] 
      then
        echo -e "${BOLD}${CYAN}${UNDERLINE} ## Backing up Music ## ${RESET}"
        echo -en "${CYAN}"
        rsync ${RSYNC_OPTIONS}  ~/Music $USER@$BACKUP_SERVER:"~/$NAME/"  
        echo -e "${RESET}"
    fi
fi

if [[ "$1" == "--pictures" || "$1" == "-p" ]];
  then
    if [[ "$2" == "-r" || "$2" == "--restore" ]]
      then
        echo -e "${BOLD}${MAGENTA}${UNDERLINE} ## Restoring Pictures to your computer ##${RESET}"
        echo -en "${MAGENTA}"
        rsync ${RSYNC_OPTIONS} $USER@$BACKUP_SERVER:"~/$NAME/Pictures" ~/
        echo -e "${RESET}"
    fi
    if [[ "$2" == "-d" || "$2" == "--delete" ]]
      then
        echo -e "${BOLD}${RED}${UNDERLINE} ## Backing up and deleting old Pictures ## ${RESET}"
	      echo -en "${RED}"
	      rsync ${RSYNC_OPTIONS}  --delete  ~/Pictures $USER@$BACKUP_SERVER:"~/$NAME/"	
	      echo -e "${RESET}"
    fi
    if [[ "$2" == "-b" || "$2" == "--backup" || "$2x" == "x" ]] 
      then
        echo -e "${BOLD}${CYAN}${UNDERLINE} ## Backing up Pictures ## ${RESET}"
        echo -en "${CYAN}"
        rsync ${RSYNC_OPTIONS}  ~/Pictures $USER@$BACKUP_SERVER:"~/$NAME/" 
        echo -e "${RESET}"
    fi
fi

if [[ "$1" == "--all" || "$1" == "-a" ]];
  then
    if [[ "$2" == "-r" || "$2" == "--restore" ]]
      then
        echo -e "${BOLD}${MAGENTA}${UNDERLINE} ## Restoring everything to your computer ##${RESET}"
	      echo -en "${MAGENTA}"
        rsync ${RSYNC_OPTIONS} $USER@$BACKUP_SERVER:"~/$NAME/" ~/
        echo -e "${RESET}"
    fi
    if [[ "$2" == "-d" || "$2" == "--delete" ]]
      then
        echo -e "${BOLD}${RED}${UNDERLINE} ## Backing up and deleting old Content ## ${RESET}"
      	echo -en "${RED}"
      	rsync ${RSYNC_OPTIONS} --exclude 'Library' --exclude '.MacOSX' --delete  ~/ $USER@$BACKUP_SERVER:"~/$NAME/"
      	echo -e "${RESET}"
    fi
    if [[ "$2" == "-b" || "$2" == "--backup" || $2x" == "x" ]] 
      then
        echo -e "${BOLD}${CYAN}${UNDERLINE} ## Backing up everything ## ${RESET}"
      	echo -en "${CYAN}"
      	rsync ${RSYNC_OPTIONS} --exclude 'Library' --exclude '.MacOSX'  ~/ $USER@$BACKUP_SERVER:"~/$NAME/"	
      	echo -e "${RESET}"
    fi
fi

## END BACKUP PROGRAM ## 


